### ISSUE TITLE
No Url Provided

### ISSUE THREAD

**Issue by eat-the-block** [satellitemx/nost#1]
Share is not working at local host. Why?

**Comment by satellitemx** [comment]
Thank you for the interest. 
Please share more information of the exception. 

Also, the Solid.js version is soon to sunset as I am planning to work on a Next.js 13 (React) refactor. This project has been the playground and may not be the best practice of many implementations.

**Comment by eat-the-block** [comment]
It is solved . Thanks for replying so quickly

**Comment by eat-the-block** [comment]
I have another issue I can’t understand how to detect an alphabet in text
editor I wanna handle popup on @ thanks
